### ISSUE TITLE
Can not enable on NextCloud 21

### ISSUE THREAD

**Issue by earlng** [ArtificialOwl/files_fulltextsearch_tesseract#40]
Hi all,

I am trying to introduces this plugin on a fresh installation of NextCloud v21.0.2

As part of my process, I use the app store to download and enable:
* Full text search
* Full text search - Elasticsearch Platform
* Full text search - Files

However, when I try to download and enable "Full text search - Files - Tesseract OCR" I get this error:
```
Client error: `GET https://github.com/daita/files_fulltextsearch_tesseract/releases/download/v20.0.1/files_fulltextsearch_tesseract-20.0.1.tar.gz` resulted in a `404 Not Found` response: Not Found
```

I get around this by manually going into `/var/html/www/custom_apps/` and manually downloading the latest version for the GitHub release using `wget` and unpacking it myself. But when I try to enable it, I get an error `An error occured during the request. Unable to proceed.`.

Checking the logs I keep getting this:
```
[PHP] Error: require_once(): Failed opening required '/var/www/html/custom_apps/files_fulltextsearch_tesseract/lib/AppInfo/../../vendor/autoload.php' (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at /var/www/html/custom_apps/files_fulltextsearch_tesseract/lib/AppInfo/Application.php#45
```

I tried looking at the line mentioned, `var/www/html/custom_apps/files_fulltextsearch_tesseract/lib/AppInfo/Application.php#45`. The output is:

```php
require_once __DIR__ . '/../../vendor/autoload.php';
```

But this seems consistent with other fulltextsearch plugins. So I don't know why this specific app is acting up. Any thoughts?

**Comment by earlng** [comment]
Found out that the `/vendor/` folder is not really part of the repository. But that it _is_ part of the release. You can grab it [here](https://github.com/ArtificialOwl/files_fulltextsearch_tesseract/releases/download/v21.0.0/files_fulltextsearch_tesseract-21.0.0.tar.gz).

**Comment by p3pp0** [comment]
@earlng my hero of today...
